
-- POSITION / 직급
INSERT INTO POSITION (PNO, PNAME) VALUES (1, '친구');
INSERT INTO POSITION (PNO, PNAME) VALUES (2, '부회장');
INSERT INTO POSITION (PNO, PNAME) VALUES (3, '회장');

-- STUDENT / 학생
INSERT INTO STUDENT (SID, SPW, SNAME, SNO, STEL, SEMAIL, SGENDER, SBIRTH, SPHOTO, PNO)
             VALUES ('aaa', '1', '강호동', 1, '010-1111-1111', 'aaa@naver.com', 'M', TO_DATE('2009-01-01', 'YYYY-MM-DD'), '1.JPG', 1);
INSERT INTO STUDENT (SID, SPW, SNAME, SNO, STEL, SEMAIL, SGENDER, SBIRTH, SPHOTO, PNO)
             VALUES ('bbb', '1', '김길환', 2, '010-2222-2222', 'bbb@naver.com', 'M', TO_DATE('2009-01-02', 'YYYY-MM-DD'), '2.JPG', 1);
INSERT INTO STUDENT (SID, SPW, SNAME, SNO, STEL, SEMAIL, SGENDER, SBIRTH, SPHOTO, PNO)
             VALUES ('ddd', '1', '최길동', 19, '010-8888-9999', 'ddd@naver.com', 'M', TO_DATE('2009-12-30', 'YYYY-MM-DD'), NULL, 2);
INSERT INTO STUDENT (SID, SPW, SNAME, SNO, STEL, SEMAIL, SGENDER, SBIRTH, SPHOTO, PNO)
             VALUES ('ccc', '1', '홍길동', 20, '010-9999-9999', 'ccc@naver.com', 'M', TO_DATE('2009-12-31', 'YYYY-MM-DD'), '20.JPG', 3);
             
SELECT * FROM STUDENT S, POSITION P WHERE P.PNO = S.PNO;
 

-- ADMIN / 관리자 선생님 테이블
INSERT INTO ADMIN (AID, APW, ANAME) VALUES ('ADMIN', '1', '선생님');

SELECT * FROM ADMIN;

-- NOTICE_BOARD 공지사항 게시판
-- 공지글번호, 관리자 아이디, 공지제목, 공지내용
INSERT INTO NOTICE_BOARD (NNO, AID, NTITLE, NCONTENT) VALUES (N_SEQ.NEXTVAL, 'ADMIN', '공지1', '공지사항내용입니다.'); 
INSERT INTO NOTICE_BOARD (NNO, AID, NTITLE, NCONTENT, NRDATE, NHIT) VALUES (N_SEQ.NEXTVAL, 'ADMIN', '공지3', '공지사항꼭확인하기', '22-03-10', 22); 

SELECT NNO, ANAME, NTITLE, NCONTENT, NRDATE FROM ADMIN A, NOTICE_BOARD N WHERE A.AID = N.AID;

COMMIT;
-- FREE_BOARD 자유게시판
INSERT INTO FREE_BOARD (FNO, SID, FTITLE, FCONTENT, FFILENAME, FREF, FSTEP, FINDENT, FIP)
    VALUES (F_SEQ.NEXTVAL, 'ccc', '오늘급식', '오늘급식돈까스래!', NULL, F_SEQ.CURRVAL, 0, 0, '127.0.0.1'); 
INSERT INTO FREE_BOARD (FNO, SID, FTITLE, FCONTENT, FFILENAME, FREF, FSTEP, FINDENT, FIP)
    VALUES (F_SEQ.NEXTVAL, 'aaa', '아', '집가고싶다', NULL, F_SEQ.CURRVAL, 0, 0, '1.1.1.1'); 
INSERT INTO FREE_BOARD (FNO, SID, FTITLE, FCONTENT, FFILENAME, FREF, FSTEP, FINDENT, FIP)
    VALUES (F_SEQ.NEXTVAL, 'aaa', '배고파', '집가고싶다', NULL, F_SEQ.CURRVAL, 0, 0, '1.1.1.2'); 

SELECT * FROM FREE_BOARD;


-- REPLY / 답변 테이블
INSERT INTO REPLY (RNO, SID, RCONTENT, RIP, FNO) 
    VALUES(R_SEQ.NEXTVAL, 'aaa', '밥', '128.1.1.1', 1);

SELECT * FROM REPLY;



